# yaml-language-server: $schema=./config.schema.yml
# Configuration template for production environment.
# REMINDER: Run `rake configure` after editing this file!

admin_handle: "1073"
final_port: 8080
final_host: "https://example.com"
# rake secret to generate a new secret key base.
secret_key_base: ""
hosts:
  backend: "http://backend:3000"
  frontend: "http://frontend:3100"
  wiki: "http://wiki:3101"
  sub_chart: "http://sub-chart:3201"
  sub_audio: "http://sub-audio:3202"
  sub_image: "http://sub-image:3203"
  sub_temp_storage: "http://sub-temp-storage:3204"
s3:
  user: "access_id"
  password: "access_token"
  bucket: "chcy"
  region: "us-east-1"
  endpoint: "https://hogehogefugafuga.r2.cloudflarestorage.com"
  public: true
  public_root: "https://cdn.example.com/"
redis_url: "redis://redis:6379/0"
postgres:
  user: "postgres"
  password: "postgres"
  database: "chcy"
  host: "postgres"
  port: 5432
# Uncomment to require Discord link to post a chart.
# discord:
#   guild_id: "123456789012345678"
#   client_id: "123456789012345678"
#   client_secret: "cl1ent53cr3t"
#   bot_token: "D1dY0uR34llyTh1nk.1W0uldPutTh3B0tT0k3nH3r3.10l"
#   warning_channel_id: "123456789012345678"

# Launch OpenObserve first to get the authorization header
# otel:
#   exporter:
#     endpoint: "http://openobserve:5080/api/default"
#     headers: "Authorization=Basic ..."
